server:
  port: 8081

spring:
  application:
    name: auth
  config:
    import: optional:classpath:application-local.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/formcraft-auth
    username: adel

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  access-token-expiration: 15m
  refresh-token-expiration: 7d

google:
  auth:
    redirect-uri: http://localhost:3000/auth/google/callback

logging:
  include-application-name: false
  pattern:
    correlation: "[${spring.application.name:}, span_id=%X{spanId:-}, trace_id=%X{traceId:-}] "
  file:
    name: logs/${spring.application.name}.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.95, 0.99
      slo:
        http.server.requests: 100ms, 300ms, 1s
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:14318/v1/traces
  otlp:
    metrics:
      export:
        enabled: false
